// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6U_jCcYzBiFCro_4PgRNh-M-u7Mpf22g',
    appId: '1:1042204341475:web:383d1e19f840b795a501d6',
    messagingSenderId: '1042204341475',
    projectId: 'surveyapp-d6565',
    authDomain: 'surveyapp-d6565.firebaseapp.com',
    storageBucket: 'surveyapp-d6565.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUBxK0K9uO-WJ9QobvPeTm4vZxP4fOZM',
    appId: '1:1042204341475:android:f542779688d50bc0a501d6',
    messagingSenderId: '1042204341475',
    projectId: 'surveyapp-d6565',
    storageBucket: 'surveyapp-d6565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0-DzKWOT5RiivwYp_Kwx0bMbpkxPfVWg',
    appId: '1:1042204341475:ios:7b4643a3f820ab3da501d6',
    messagingSenderId: '1042204341475',
    projectId: 'surveyapp-d6565',
    storageBucket: 'surveyapp-d6565.appspot.com',
    iosClientId: '1042204341475-gq22440ntjiaikh3925dghl92bgrso3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0-DzKWOT5RiivwYp_Kwx0bMbpkxPfVWg',
    appId: '1:1042204341475:ios:7b4643a3f820ab3da501d6',
    messagingSenderId: '1042204341475',
    projectId: 'surveyapp-d6565',
    storageBucket: 'surveyapp-d6565.appspot.com',
    iosClientId: '1042204341475-gq22440ntjiaikh3925dghl92bgrso3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyApp',
  );
}
